import type { NextPage } from 'next'
import Head from 'next/head'
import Posts from '../components/Posts'
import styles from '../styles/Home.module.css'

export const getStaticProps = async () => {
  const response = await fetch('http://localhost:3000/api/posts')
  const posts = await response.json()
  if(!posts) {
    return 'No data'
  }

  return {
    props: {posts}
  }
  
}

const Home: NextPage = ({posts}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Only Next</title>
        <meta name="description" content="Generated by create next app" />

      </Head>
    <Posts posts={posts}/>
    </div>
  )
}



export default Home
